const express = require('express');
const router  = express.Router();
const addshop = require('../controller/addShopController');
const buybook = require('../controller/buyBookController');
const buysell = require('../controller/buyAndSellController');
router.get('/',addshop.showMarket);
router.get('/add/:id',addshop.addtocart);
router.post('/add/',addshop.cartToMarket);
router.post('/:id',buysell.completeBuy);
module.exports = router;